packages:
  - docs/
  - e2e/
  - plugins/*/*
  - themes/*
  - tools/*
catalog:
  '@vuepress/bundler-vite': 2.0.0-rc.20
  '@vuepress/bundler-webpack': 2.0.0-rc.20
  '@vueuse/core': ^13.0.0
  sass: ^1.86.0
  sass-embedded: ^1.86.0
  sass-loader: ^16.0.5
  vue: ^3.5.13
  vuepress: 2.0.0-rc.20
